# Generated by Django 2.2 on 2020-08-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_auto_20200801_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewslot',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_slots', to='usermanagement.CandidateProfile'),
        ),
        migrations.AlterField(
            model_name='interviewslot',
            name='interviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviewer_slots', to='usermanagement.InterviewerProfile'),
        ),
    ]
